master:
  image: redis:3
  volumes:
  - ./redis/redis.conf:/usr/local/etc/redis/redis.conf 
  - ./data/master:/data/redis_cache
  ports:
    - "6379:6379"  

slave:
  image: redis:3
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  volumes:
  - ./data/slave:/data/redis_cache

  ports:
    - "6380:6379" 

sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave

  volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf 
    - ./data/sentinel:/data/redis_cache    
  ports:
    - "26379:26379"
